@startuml
participant ClientInitializer
ClientInitializer -> Client: <<create>>
activate Client
ClientInitializer -> Client: initServerConnection(ClientServerNetworkInfo)


Client -> ServerMessageDispatcher: <<create>> (ClientServerNetworkInfo)
activate ServerMessageDispatcher

ServerMessageDispatcher -> CommunicationNetworkInterface: <<create>> (ClientServerNetworkInfo)
activate CommunicationNetworkInterface
ServerMessageDispatcher -> CommunicationNetworkInterface: addObserver(this)
ServerMessageDispatcher --> Client:

Client -> ServerMessageDispatcher: addDispatchObserver(this)
Client -> ServerMessageDispatcher: createPersistentServerConnection()

ServerMessageDispatcher -> CommunicationNetworkInterface: setServerSocketConnection(int)
CommunicationNetworkInterface --> ServerMessageDispatcher :

ServerMessageDispatcher -> CommunicationNetworkInterface: handleInboundPacketRequests()
CommunicationNetworkInterface -> CommunicationNetworkInterface: writeDataPacket(DataPacket)
CommunicationNetworkInterface -> CommunicationNetworkInterface: startNetworkInterfaceMonitor(DataPacket)
deactivate ServerMessageDispatcher
deactivate Client
@enduml
