package edu.nyu.cess.remote.common.app;

/**
 * Created by aruff on 2/29/16.
 */
public enum ErrorType
{
	SAME_APP_SAME_STATE, SAME_APP_ALREADY_STOPPED, SAME_APP_ALREADY_RUNNING, OTHER_APP_ALREADY_RUNNING, FAILED_TO_START, SECURITY_ERROR, IO_ERROR, APP_ALREADY_STOPPED, NO_ERROR
}
